---
# Redhat based OS
- name: Redhat | get rundeck repo rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: yes
  tags:
    - rundeck
    - install
    - packages

- name: Redhat | Install rundeck via yum
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  notify:
    - start rundeck
  tags:
    - rundeck
    - install
    - packages
  items:
  - "rundeck-{{ rundeck_version }}"
  - "rundeck-config-{{ rundeck_version }}"

- name: set rundeck_package_command for redhat
  set_fact:
    rundeck_package_command: yum info
